### PR TITLE
Update vscode-stylelint to v0.85.0

### PR DESCRIPTION
**Pull request by rchl**
Also moved the update script and updated it a bit to be more consistent with other similar scripts.

### CODE REVIEW

**Review by predragnikolic — APPROVED** [review]
- the server starts,
- I get autocomplete in LSP-stylelint.sublime-settings and sublime-project files.

Everything else looks great :+1: :)

**Comment by predragnikolic** [comment]
Just a question regarding dependabot, do we really need it for this repo?
The package.json has a lot of deps:
```
   "fast-diff": "^1.2.0",
    "kind-of": "^6.0.3",
    "lodash": "^4.17.15",
    "path-is-inside": "^1.0.2",
    "stylelint": "^13.6.0",
    "vscode-languageclient": "^6.2.0-next.1",
    "vscode-languageserver": "^6.2.0-next.1",
    "vscode-languageserver-textdocument": "^1.0.1",
    "vscode-languageserver-types": "^3.16.0-next.1",
    "vscode-uri": "^2.1.1"
  },
  "devDependencies": {
    "@types/kind-of": "^6.0.0",
    "@types/lodash": "^4.14.151",
    "@types/path-is-inside": "^1.0.0",
    "@types/stylelint": "^9.10.1",
    "@types/tape": "^4.13.0",
    "@types/vscode": "1.43.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.1",
    "eslint-config-stylelint": "^11.1.0",
    "find-pkg": "^2.0.0",
    "find-root": "^1.1.0",
    "npm-run-all": "^4.1.5",
    "nyc": "^15.0.1",
    "p-wait-for": "^3.1.0",
    "pkg-dir": "^4.2.0",
    "prettier": "^1.19.1",
    "rmfr": "^2.0.0",
    "stylelint-processor-glamorous": "^0.3.0",
    "stylelint-processor-styled-components": "^1.10.0",
    "tape": "^4.13.2",
    "typescript": "^3.9.2",
    "vscode-test": "^1.3.0",
    "zen-observable": "^0.8.15"
```
Getting a notification when each of the dependencies gets updated can cause too much noise in my inbox.

Do you have a reason why you would add dependabot?

**Comment by rchl** [comment]
I don't know what I was thinking. This repo shouldn't use dependabot.

**Comment by predragnikolic** [comment]
A direct commit removing dependabot is also an option :)

**Comment by rchl** [comment]
Yes, reverted on master.

**Pull request merged**
