### PR TITLE
update server to 1.2.2

### PR DESCRIPTION
**Pull request by predragnikolic**

### CODE REVIEW

**Comment by predragnikolic** [comment]
@rchl if you want, can you take a look? (if not I will probably merge it next week)

This PR closes this PR -> https://github.com/sublimelsp/LSP-stylelint/pull/24

**Comment by rchl** [comment]
There is already my PR #24.

The reason I wasn't to eager to integrate it is that it's a big breaking change. The new version requires that all dependencies like stylelint and various pre-processors for specific languages are included in the project and then the LSP-stylelint settings are changed to enable support for those languages.

Also it deprecates support for Stylelint 2 so in projects that use it it shows a warning that things might not work.

I was thinking of doing something to include stylelint 3 that we could fallback too but that's only part of the problem. We'd also need to configure it properly for the languages used in the project so I think it's not really feasible.

**Comment by rchl** [comment]
So with that said, I don't see why not continue with #24 instead. Assuming that this is what we actually want.
Personally I've switched my projects to v14 and will be fine with that but I'd expect a lot of disgruntled users complaining about this no longer working.

**Comment by predragnikolic** [comment]
Yeah, lets continue with #24

**Pull request closed without merging**
