### PR TITLE
Update vscode-stylelint to v0.87.6

### PR DESCRIPTION
**Pull request by rchl**
All dependencies are now bundled so dependencies don't need to be
installed.

### CODE REVIEW

**Review by predragnikolic — APPROVED** [review]

**Comment by predragnikolic** [comment]
Will you wait a bit till all people get the latest version of `lsp_utils` before publishing a new version of 
`LSP-stylelint`? 

I haven't followed the progress of PC, I knew that there were some issues of dependencies not updating, so I don't know if that issue was fixed on the PC side.

**Comment by rchl** [comment]
It wasn't fixed so updating dependencies can be a bit erratic.

I can wait a bit but even after many days the dependency can still not get updated so we can't guarantee anything.

**Comment by rchl** [comment]
At least this one won't break without the corresponding lsp_utils change. It will just install some unnecessary dependencies.

**Comment by predragnikolic** [comment]
> At least this one won't break without the corresponding lsp_utils change. It will just install some unnecessary dependencies.

Are you sure?
Without the changes from lsp_utils (skip_npm_install),
I am getting this error:

image

**Comment by rchl** [comment]
Oh, right. That's because I've decided not to include the lock file.

**Pull request merged**
